### ISSUE TITLE
Alternative Viewer

### ISSUE THREAD

**Issue by Courtsilius** [cgtuebingen/hyperrealistic_indoor_streetview#19]
See if there is a better alternative to our current viewer to boost performance. Some work better than others, one example:

[https://antimatter15.com/splat/](https://antimatter15.com/splat/)

**Comment by amigo074** [comment]
Here's a list with a loooot of viewers:

https://github.com/MrNeRF/awesome-3D-gaussian-splatting?tab=readme-ov-file#viewers

**Comment by NorbiPDF** [comment]
## Alternative Viewers
### Antimatter15 (https://github.com/antimatter15/splat)
Viewer tested the scene with around 120.000 splats
- Can maintain **constantly** around **60fps**
- **Fast** movement **doesn´t reduce** fps

Con:
- Overall quality is reduced **minimally** *(probably to maintain good performance)*

See pictures:
![Antimatter](https://github.com/cgtuebingen/hyperrealistic_indoor_streetview/assets/148484506/11a84c7c-7482-4970-a2d0-52aa2f3963f6)
![Antimatter2](https://github.com/cgtuebingen/hyperrealistic_indoor_streetview/assets/148484506/ae82410b-843f-4835-b4aa-854826d85a14)


### WebGL Vercel (https://webgl-gaussian-splatting.vercel.app)
Viewer tested the scene with around 120.000 splats
- Can select preview resolution to reduce fps drop during movement
- **Acceptable** performance during **movement** of the camera when **preview resolution** is set **low**
- **Good** picture quality when camera **stationary**

Con:
- When preview resolution ist set low and **fast movement** of the camera occures, the scene looks **blurry**
- When **preview resolution** is set **higher** scene starts **lagging** during **movement**

See pictures:
![WebGL](https://github.com/cgtuebingen/hyperrealistic_indoor_streetview/assets/148484506/701f112a-a75c-408d-886a-dfc10793a54d)
![WebGL2](https://github.com/cgtuebingen/hyperrealistic_indoor_streetview/assets/148484506/53dfff14-ebac-448a-85ec-8c1f03ac1f99)

### WebGPU 1 (https://github.com/cvlab-epfl/gaussian-splatting-web)
Viewer tested the scene with 120.000 splats

- **Very poor performance** ( 1-4 fps)
- Output picture is square

### WebGPU 3 (https://github.com/KeKsBoTer/web-splat)
Viewer tested the scene with around 5.000.000 splats (demo)
- Somewhat **laggy performance** tho very **high** number of **splats**
- Some splats were **flickering** making the scene look bad*ish*

### Three.js (https://github.com/mkkellogg/GaussianSplats3D)
Viewer tested locally the scene with 120.000 splats
- Good performance even during camera movement

Con:
- Sometimes scene lagged for longer time *(about 0.5 - 1 seconds)*

### A-Frame (https://github.com/quadjr/aframe-gaussian-splatting) 
Demo tested 
*(code is derived from the WebGL implementation developed by [antimatter15](https://github.com/antimatter15/splat))*
- could maintain **constant 60fps** during **fast movement**

**Comment by NorbiPDF** [comment]
## Conclusion
Since it would take too much time to implement antimatter15 in react-three-fiber, and no other reviewed viewer in react-three-fiber meets our needs, we've decided to optimize the viewer we're already using in the project.
