### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by Courtsilius** [cgtuebingen/hyperrealistic_indoor_streetview#28]
We need to find out where we can get a camera from

**Comment by amigo074** [comment]
Currently using Pascals Camera for test footage. Once we have an appointment with the KIMS we will get a better camera.

**Comment by nhergen** [comment]
If the quality of the Images is not sufficient, please give feedback here. That way we can determine weather we need a better camera

**Comment by C3YLA** [comment]
Image and Video Review:
Videos:
-  Couldn´t get any good positions out of the videos (use autofocus for the new videos)
Images:
- "Elektro-Raum": could only get positions for 3 images, the images are (probably) too dark
- "Musik": TBA
- "Fotolabor": TBA
- "Holz-Raum": TBA
- "Lager-Raum": TBA
- "Medien-Raum": TBA
- "Medien&Textil-Raum": TBA
