### ISSUE TITLE
Research: Ideal way to take photos/positions/etc...

### ISSUE THREAD

**Issue by Courtsilius** [cgtuebingen/hyperrealistic_indoor_streetview#30]
Read up on COLMAP, at least the part on how to create the "perfect" image and present your findings in short form to the team

**Comment by amigo074** [comment]
Ressources:

- https://medium.com/@heyulei/capture-images-for-gaussian-splatting-81d081bbc826

**Comment by amigo074** [comment]
I guess we can move this one to done and just add infomration as we get more experience with the data aquisition
