### ISSUE TITLE
User Authentication (SSH)

### ISSUE THREAD

**Issue by Courtsilius** [cgtuebingen/hyperrealistic_indoor_streetview#4]
add accounts to the server:
- useraccounts
- account for actions (edit actions script accordingly)

**Comment by FabiKogWi** [comment]
Installed Dropbox on the server in the ghactions folder. 
The Dropbox daemon is running in the background to enable filesync
There is a symlink between the public folder in the dropbox folder and the public folder in the hyperrealistic_indoor_streetview folder. To use do the following:
- Create a dropbox account
- Download Dropbox
- Use the link in the Discord
This enables Drag & Drop upload of splats from the explorer into the public folder on the server
