### ISSUE TITLE
Möglichkeit von Github Pages prüfen

### ISSUE THREAD

**Issue by Courtsilius** [cgtuebingen/hyperrealistic_indoor_streetview#54]
... und generell ein bisschen einlesen in Hosting.

https://docs.docker.com/desktop/wsl/
https://github.com/docker/getting-started
https://github.com/Dcard/yarn-plugins/tree/master/packages/docker-build
https://github.com/Gurenax/node-express-docker

**Comment by LouisHain** [comment]
Using github pages probably isnt feasible in a timely manner, as it only allows static site hosting, which would require major rewrites of packages etc.
We now settled on using @Courtsilius private server for the duration of the Teamprojekt. http://46.38.250.233:3000/
After that, switching to the servers of the splatted location or hosting on uni servers seems to be the best solution.

**Comment by FabiKogWi** [comment]
The [yarn workspace to docker image plugin](https://github.com/Dcard/yarn-plugins/tree/master/packages/docker-build) breaks my yarn installation so I can no longer run yarn dev to run the server (or any other yarn command), necessitating a full yarn reinstall.
Error Message: 
''r.Command.String is not a function (when initializing @yarnpkg/plugin-docker-build, defined in /C:/Users/User/Desktop/Code/Teamprojekt/hyperrealistic_indoor_streetview/.yarnrc.yml)
    at C:\Users\User\Desktop\Code\Teamprojekt\hyperrealistic_indoor_streetview\.yarn\plugins\@yarnpkg\plugin-docker-build.cjs:5:7931
    at factory (C:\Users\User\Desktop\Code\Teamprojekt\hyperrealistic_indoor_streetview\.yarn\plugins\@yarnpkg\plugin-docker-build.cjs:5:8395)''
