### ISSUE TITLE
Design Ausarbeiten für Landingpage

### ISSUE THREAD

**Issue by Courtsilius** [cgtuebingen/hyperrealistic_indoor_streetview#6]
* As a User I want to see something 
* As a User I want to see blocks of text concerning location 
* Design 
* Informationen zum KIMS 
* Informationen zur Steuerung 
* Link zum GitHub 
* Übersicht mit Räumen 
* Generellen Start Button 
* Licenses/Acknowledgements

**Comment by nhergen** [comment]
<iframe style="border: 1px solid rgba(0, 0, 0, 0.1);" width="800" height="450" src="https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Fboard%2FhSyeO4V9EjXSFJF2DscZPn%2FLanding-Page-Konzept%3Fnode-id%3D0-1%26t%3Duvq1NUMdqj2a0ngh-1" allowfullscreen></iframe>

**Comment by nhergen** [comment]
![Image](https://github.com/cgtuebingen/hyperrealistic_indoor_streetview/assets/115873998/8edc49b1-7711-486e-9330-ff54efc6edb0)


See concept here: https://www.figma.com/board/hSyeO4V9EjXSFJF2DscZPn/Landing-Page-Konzept?node-id=0-1&t=uvq1NUMdqj2a0ngh-1

**Comment by LouisHain** [comment]
The design implements everything we wanted and more and works well as a initial landingpage.
Only thing missing is the info about the controls, which probably is better kept in the viewer itself.
